
export const sample_foods = [
  {
    id: '1',
    name: 'Muhammadjon',
    price: 10,
    favorite: false,
    origins: ['Uzbekistan'],
    stars: 5.0,
    imageUrl: 'assets/FRANCE-4.jpg',
    tags: ['numberOne', 'Muhammad'],
  },
  {
    id: '2',
    name: 'Ananas',
    price: 15,
    favorite: true,
    origins: ['USA'],
    stars: 4.5,
    imageUrl: 'assets/photo-1.jpg',
    tags: ['Ananas', 'Fruits'],
  },
  {
    id: '3',
    name: 'Anor',
    price: 8,
    favorite: true,
    origins: ['Spain'],
    stars: 4.2,
    imageUrl: 'assets/photo-2.jpg',
    tags: ['Anor', 'Fruits'],
  },
  {
    id: '4',
    name: 'qulpnay',
    price: 12,
    favorite: false,
    origins: ['Italy'],
    stars: 4.8,
    imageUrl: 'assets/photo-3.jpg',
    tags: ['Qulpnay', 'Fruits'],
  },
  {
    id: '5',
    name: 'Mandarin',
    price: 11,
    favorite: true,
    origins: ['Mexico'],
    stars: 4.7,
    imageUrl: 'assets/photo-4.jpg',
    tags: ['Mandarin', 'Spicy', 'Fruits'],
  },
  {
    id: '6',
    name: 'Banana',
    price: 9,
    favorite: false,
    origins: ['France'],
    stars: 4.0,
    imageUrl: 'assets/photo-5.jpg',
    tags: ['Banana', 'Elegant', 'Fruits'],
  },
  {
    id: '7',
    name: 'Apple',
    price: 14,
    favorite: true,
    origins: ['Germany'],
    stars: 4.6,
    imageUrl: 'assets/photo-6.jpg',
    tags: ['Apple', 'Sausages', 'Fruits'],
  },
  {
    id: '8',
    name: 'Gilos',
    price: 7,
    favorite: false,
    origins: ['Greece'],
    stars: 4.1,
    imageUrl: 'assets/photo-8.jpg',
    tags: ['Gilos', 'Fruits'],
  },
  {
    id: '9',
    name: 'Kivi',
    price: 13,
    favorite: true,
    origins: ['Japan'],
    stars: 4.9,
    imageUrl: 'assets/photo-7.jpg',
    tags: ['Kivi', 'Fruits'],
  },
  {
    id: '10',
    name: 'Mango',
    price: 10,
    favorite: true,
    origins: ['India'],
    stars: 3.4,
    imageUrl: 'assets/photo-9.jpg',
    tags: ['Mango', 'Fruits'],
  },
];


export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];